Bug fix
Use integer division when appropriate. This solves the following error
that appeared during tests:

    TypeError: object of type <class 'float'> cannot be safely interpreted as an integer

This was causing 14 tests to fail when running on python 3.6, namely

test_aero_analysis_no_symmetry.py:Test.test
test_aero_analysis_no_symmetry_wavedrag.py:Test.test
test_aero_opt_no_symmetry.py:Test.test
test_aero_opt_wavedrag.py:Test.test
test_geometry_mesh_transformations.py:Test.test_dihedral
test_geometry_mesh_transformations.py:Test.test_rotate
test_geometry_mesh_transformations.py:Test.test_scalex
test_geometry_mesh_transformations.py:Test.test_shearx
test_geometry_mesh_transformations.py:Test.test_sheary
test_geometry_mesh_transformations.py:Test.test_shearz
test_geometry_mesh_transformations.py:Test.test_stretch
test_geometry_mesh_transformations.py:Test.test_sweep
test_geometry_mesh_transformations.py:Test.test_taper
test_v1_aerostruct_opt.py:Test.test

Now they pass.